version: '3'
services:
  passmonki_dev:
    env_file:
      - .env
    image: "docker-registry.local:5000/passmonki_${PASSV}"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - passmonki_dev:/autoseg/var/www/sso/public
  apache:
    image: "docker-registry.local:5000/apache_${WEBV}"
    volumes:
      - passmonki_dev:/autoseg/var/www/sso/public/
      - /etc/pki/CA/certs/:/etc/httpd/certs
    ports:
      - "8080:80"
      - "443:443"
    links:
      - 'passmonki_dev'
volumes:
  passmonki_dev:
