version: '3'
services:
  passmonki:
    env_file:
      - .env
    environment:
      - RAILS_ENV=${RAILS_ENV}
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - passmonki:/autoseg/var/www/sso/public
  apache:
    build: apache-dockerfile/
    volumes:
      - passmonki:/autoseg/var/www/sso/public/
      - /etc/pki/CA/certs/:/etc/httpd/certs
    ports:
      - "8080:80"
      - "443:443"
    links:
      - 'passmonki'
volumes:
  passmonki:
